name: Update installer
run-name: Update installer to ${{ inputs.release }}
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Yagna release tag (for example v0.17.7)'
        required: true
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - run: |
          cp setup-kvm.sh dist/
          python gen.py "${{ inputs.release }}"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
